import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:3000/tai-lieu', { waitUntil: 'networkidle' })
await page.waitForTimeout(2000)
const before = await page.evaluate(() => ({ cls: document.documentElement.className, bg: getComputedStyle(document.body).backgroundColor }))
console.log('before:', JSON.stringify(before))
const btn = page.locator('button[aria-label="Đổi giao diện sáng tối"]').first()
console.log('toggle count:', await page.locator('button[aria-label="Đổi giao diện sáng tối"]').count())
await btn.click()
await page.waitForTimeout(900)
const after = await page.evaluate(() => ({ cls: document.documentElement.className, bg: getComputedStyle(document.body).backgroundColor, ls: localStorage.getItem('mapdocs:theme') }))
console.log('after:', JSON.stringify(after))
await page.screenshot({ path: 'screenshots/dark-tailieu.png' })
await page.reload({ waitUntil: 'networkidle' })
await page.waitForTimeout(1500)
const persist = await page.evaluate(() => ({ cls: document.documentElement.className, ls: localStorage.getItem('mapdocs:theme') }))
console.log('after reload:', JSON.stringify(persist))
await browser.close()
